In [31]:
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd

In [2]:
housing = fetch_california_housing()

In [49]:
housing['target_names']

['MedHouseVal']

In [47]:
housing_dataframe = pd.DataFrame(housing['data'], columns = housing['feature_names'])

In [50]:
housing_dataframe['MedHouseVal'] = housing['target']

In [12]:
housing['feature_names']

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [20]:
housing['data'][0,:]

array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
        322.        ,    2.55555556,   37.88      , -122.23      ])

In [21]:
X = housing['data']
y = housing['target']

In [23]:
model = LinearRegression()

In [24]:
MODEL = model.fit(X,y)

In [25]:
MODEL.coef_

array([ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,  6.45065694e-01,
       -3.97638942e-06, -3.78654265e-03, -4.21314378e-01, -4.34513755e-01])

In [26]:
MODEL.intercept_

-36.941920207184396

In [28]:
MODEL.predict([[3,4,5,4,3,4,7,2]])

array([-37.3838309])

In [29]:
housing['feature_names']

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [34]:
A =np.array([1,2,3,4,5,6,7,8])

In [41]:
MODEL.predict([[1,2,3,4,5,6,7,8]])

array([-40.67610853])

In [51]:
housing_dataframe.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

In [54]:
housing_dataframe.to_csv('C:/Users/sthapam/OneDrive - Indiana University/LinearRegressionApp/housing.csv',index = False)